Repository konveyor/move2kube-transformers, pull requests merged in 2021-12, with the labels that each got.

#6 ci: make this repo part of the release workflow
  .github/workflows/release.yml
  releasenotes-config.js
Labels: ci

#7 fix: Updated the ingress-annotator to reflect transformer definition changes
  ingress-annotation-customization/ingress-annotator/ingress-annotator.star
  ingress-annotation-customization/ingress-annotator/ingress-annotator.yaml
  ingress-annotation-customization/kubernetes/kubernetes.yaml
  ingress-annotation-customization/tekton/tekton.yaml
Labels: fix

#8 feat: add an example on how to use the intercept feature
  add-annotation-advanced/ingress-annotator/ingress-annotator.star
  add-annotation-advanced/ingress-annotator/ingress-annotator.yaml
  add-annotation-advanced/kubernetes/kubernetes.yaml
  add-annotation-advanced/tekton/tekton.yaml
  add-annotation-simple/ingress-annotator.star
  add-annotation-simple/ingress-annotator.yaml
Labels: feat

#9 fix: update parameterizer yamls to reflect the new transformer yaml format
  parameterizers/advanced-example/parameterizers.yaml
  parameterizers/simple-example/parameterizers.yaml
Labels: fix

#10 feat: Added a collection of transformer samples to include Move2Kube changes
  add-annotation-simple/ingress-annotator.yaml
  base-image-change/nodejs.yaml
  base-image-change/templates/Dockerfile
  folder-customizer/kubernetes.yaml
  parameterizers/simple-example/parameterizers.yaml
  parameterizers/simple-example/replicas-parameterizer.yaml
  script-inject/nodejs.yaml
  script-inject/templates/Dockerfile
  script-inject/templates/hello-nodejs.sh
Labels: feat

#11 feat: Added helm chart generator
  custom-helmchart-gen/customhelmchartgen.star
  custom-helmchart-gen/customhelmchartgen.yaml
  custom-helmchart-gen/templates/helm-chart/{{ .ServiceName }}/Chart.yaml
  custom-helmchart-gen/templates/helm-chart/{{ .ServiceName }}/templates/{{ .ServiceName }}-deployment.yaml
  custom-helmchart-gen/templates/helm-chart/{{ .ServiceName }}/templates/{{ .ServiceName }}-ingress.yaml
  custom-helmchart-gen/templates/helm-chart/{{ .ServiceName }}/templates/{{ .ServiceName }}-service.yaml
  custom-helmchart-gen/templates/helm-chart/{{ .ServiceName }}/values.yaml
Labels: feat

#12 fix: Removed advanced ingress annotator and update advanced parameterizer
  add-annotation-advanced/ingress-annotator/ingress-annotator.star
  add-annotation-advanced/ingress-annotator/ingress-annotator.yaml
  add-annotation-advanced/kubernetes/kubernetes.yaml
  add-annotation-advanced/tekton/tekton.yaml
  parameterizers/advanced-example/parameterizers.yaml
Labels: fix

#13 fix: updated the folder customizer yaml
  folder-customizer/kubernetes.yaml
Labels: fix
