Repository konveyor/move2kube-transformers, pull requests merged in 2022-01, with the labels that each got.

#15 fix: Updated the custom helm chart transformer with new service name filed
  custom-helmchart-gen/customhelmchartgen.star
Labels: fix

#16 fix: fix paramterizers config
  parameterizers/advanced-example/parameterizers.yaml
  parameterizers/simple-example/parameterizers.yaml
Labels: fix

#18 feat: Add download script
  scripts/download.sh
Labels: feat

#19 chore: Rename ingress annotator transformer dir name
  add-custom-kubernetes-annotation/ingress-annotator.star
  add-custom-kubernetes-annotation/ingress-annotator.yaml
Labels: chore

#20 chore: rename custom dockerfile transformer
  custom-dockerfile/nodejs.yaml
  custom-dockerfile/templates/Dockerfile
Labels: chore

#21 docs: merge script inject transformer into custom dockerfile transformer
  custom-dockerfile-custom-files/nodejs.yaml
  custom-dockerfile-custom-files/templates/Dockerfile
  custom-dockerfile-custom-files/templates/start-nodejs.sh
  custom-dockerfile/nodejs.yaml
  script-inject/templates/Dockerfile
Labels: docs

#22 fix: update custom parameterizer
  custom-helm-kustomize-octemplates-parameterization/README.md
  custom-helm-kustomize-octemplates-parameterization/deployment-parameterizers.yaml
  custom-helm-kustomize-octemplates-parameterization/parameterizers.yaml
  parameterizers/advanced-example/README.md
  parameterizers/advanced-example/container-name-parameterizer.yaml
  parameterizers/simple-example/README.md
  parameterizers/simple-example/parameterizers.yaml
  parameterizers/simple-example/replicas-parameterizer.yaml
  scripts/download.sh
Labels: fix

#23 chore: rename custom-helmchart-gen transformer
  add-custom-files-directories-in-custom-locations/customhelmchartgen.star
  add-custom-files-directories-in-custom-locations/customhelmchartgen.yaml
  add-custom-files-directories-in-custom-locations/templates/helm-chart/{{ .ServiceName }}/Chart.yaml
  add-custom-files-directories-in-custom-locations/templates/helm-chart/{{ .ServiceName }}/templates/{{ .ServiceName }}-deployment.yaml
  add-custom-files-directories-in-custom-locations/templates/helm-chart/{{ .ServiceName }}/templates/{{ .ServiceName }}-ingress.yaml
  add-custom-files-directories-in-custom-locations/templates/helm-chart/{{ .ServiceName }}/templates/{{ .ServiceName }}-service.yaml
  add-custom-files-directories-in-custom-locations/templates/helm-chart/{{ .ServiceName }}/values.yaml
  customize-inbuilt-transformer-behaviour/kubernetes.yaml
Labels: chore

#24 chore: merge changing kubernetes output directory transformer into custom dockerfile transformer
  custom-dockerfile-change-inbuilt-behavior/kubernetes/kubernetes.yaml
  custom-dockerfile-change-inbuilt-behavior/nodejs/nodejs.yaml
  custom-dockerfile-change-inbuilt-behavior/nodejs/templates/Dockerfile
  custom-dockerfile-change-inbuilt-behavior/nodejs/templates/start-nodejs.sh
Labels: chore

#25 chore: rename in-built as built-in
  add-custom-files-directories-in-custom-locations/transformer.yaml
  add-custom-kubernetes-annotation/transformer.yaml
  custom-dockerfile-change-built-in-behavior/kubernetes/transformer.yaml
  custom-dockerfile-change-built-in-behavior/nodejs/templates/Dockerfile
  custom-dockerfile-change-built-in-behavior/nodejs/templates/start-nodejs.sh
  custom-dockerfile-change-built-in-behavior/nodejs/transformer.yaml
  custom-helm-kustomize-octemplates-parameterization/transformer.yaml
Labels: chore
